version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: fe
    networks:
      - mon_net

  backend1:
    build: ./backend
    container_name: backend1
    environment:
      - INSTANCE_ID=backend-1
    networks:
      - mon_net

  backend2:
    build: ./backend
    container_name: backend2
    environment:
      - INSTANCE_ID=backend-2
    networks:
      - mon_net

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend1
      - backend2
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - mon_net

  # ===========================
  # GOACCESS REALTIME (LOCAL)
  # ===========================
  goaccess:
    image: allinurl/goaccess:latest
    container_name: goaccess
    ports:
      - "7890:7890"
    networks:
      - mon_net
    volumes:
      - ./nginx/logs:/logs:ro
      - ./goaccess/etc/goaccess.conf:/etc/goaccess/goaccess.conf:ro
    command: >
      goaccess /logs/access.log
        --config-file=/etc/goaccess/goaccess.conf
        --real-time-html
        --port=7890
        --origin=http://localhost
    restart: unless-stopped

networks:
  mon_net:
    driver: bridge
